version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cmd:/shuffle-bot/cmd
      - ./internal:/shuffle-bot/internal
      - ./team.json:/shuffle-bot/team.json
    restart: always